#!/bin/sh

set -e
#set -x

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst.sqlite3 


dbc_generate_include_args="-U -o template_infile=/usr/lib/csas-authorize/.env.template"
dbc_generate_include=template:/etc/csas-authorize/csas-authorize.env
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="664"
dbc_dbfile_owner="www-data:www-data"
dbc_dbfile_perms="0664"

dbc_go csas-authorize "$@"


#DEBHELPER#
